version: 1.2
workflows:
  - name: gatk4-preprocessing-custom
    subclass: WDL
    primaryDescriptorPath: /processing-for-variant-discovery-gatk4/processing-for-variant-discovery-gatk4.wdl
    testParameterFiles:
      - /processing-for-variant-discovery-gatk4/test_data/pre-processing-for-variant-discovery-gatk4-test-data.json
